steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull asia-northeast1-docker.pkg.dev/$PROJECT_ID/ahc0xx/executer:latest || exit 0
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/ahc0xx/executer:latest",
        "--cache-from",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/ahc0xx/executer:latest",
        ".",
      ]
images:
  ["asia-northeast1-docker.pkg.dev/$PROJECT_ID/ahc0xx/executer:latest"]
